# -*- coding: utf-8 -*-
import json

from jinja2 import Environment, PackageLoader

jinja2_env = Environment(
    loader=PackageLoader("ecs_codegen", "templates"),
    autoescape=False,
)

jinja2_env.globals["autogen_warning"] = (
    "/* This file is autogenerated by ecs_codegen. Do not edit this file manually */"
)


def c_str(input: str):
    """Escape a string to be used in C code."""
    return json.dumps(input)


jinja2_env.filters["c_str"] = c_str
