{ "columns":12,
 "image":"tileset_base.png",
 "imageheight":936,
 "imagewidth":914,
 "margin":0,
 "name":"tileset_base",
 "spacing":2,
 "tilecount":156,
 "tiledversion":"1.10.2",
 "tileheight":70,
 "tiles":[
        {
         "id":19,
         "type":"ladder"
        }, 
        {
         "id":21,
         "type":"ladder"
        }, 
        {
         "id":31,
         "type":"ladder"
        }],
 "tilewidth":70,
 "type":"tileset",
 "version":"1.10"
}