name: Build with CMake

on:
  push: # Trigger on push events

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the repository
        with:
          recursive: true  # Checkout submodules recursively
      - name: Install dependencies
        run: sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
      - name: Configure CMake
        run: |
            ls -lah libs
            ls -lah libs/nbnet
            cmake -B build -S .
      - name: Build
        run: cmake --build build --config Release
